"""
Django settings for Mypro project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path


# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent



# Security

SECRET_KEY = 'django-insecure-(q@gi6--d!6cf35yr3v#dp^=9^)k+u)d%9!vpg4_w)^k5e^mv#'


DEBUG = False


ALLOWED_HOSTS = [
    ".vercel.app",
    "localhost",
    "127.0.0.1",
    "django-5fgbppi1d-ahmadsulaimankhails-projects.vercel.app"
]


# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'App',

]



MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    # Static files in production
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]



ROOT_URLCONF = 'Mypro.urls'



TEMPLATES = [

    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / "templates"
        ],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]



WSGI_APPLICATION = 'Mypro.wsgi.application'





# Database

DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.sqlite3',

        'NAME': BASE_DIR / 'db.sqlite3',

    }

}





# Password validation

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

]





# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True





# Static files

STATIC_URL = "/static/"


STATIC_ROOT = BASE_DIR / "staticfiles"


if (BASE_DIR / "static").exists():

    STATICFILES_DIRS = [
        BASE_DIR / "static"
    ]



STORAGES = {

    "staticfiles": {

        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",

    },

}





# Vercel CSRF

CSRF_TRUSTED_ORIGINS = [

    "https://django-liard-gamma.vercel.app"

]





DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'